### ISSUE TITLE
again.....  VM1347:1 Uncaught ReferenceError: todoList is not defined     at <anonymous>:1:1

### ISSUE THREAD

**Issue by DBNoisemaker** [gordonmzhu/questions#32]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/936343

### Include a live demo link so that I can run your code. 

https://plnkr.co/edit/3OZOAzAde4DbQt0yQLqo?p=preview

### Explain the exact steps I need to take to replicate the problem. 

try running it and adding todos to the list. 

### What did you expect to happen? 

I expected it to work

### What actually happened? 

VM1347:1 Uncaught ReferenceError: todoList is not defined     at <anonymous>:1:1

### Describe what you've done so far to troubleshoot the problem. 

This is the second time I've run into this problem, when any attempt at testing in preview target mode gives me "todoList is not defined at 1:1" so it's impossible to follow along with the videos in any sort of productive way and is obviously a bit frustrating.  The same thing happened last time I had this problem you said there were typos in a section of the code that was exactly as you typed it, yet there was a type-o in a different section, though it didn't fix the problem.  

This is the second time around and same thing.
It seems to start not working around Version 6.  
Let me know what you think. thank you.

**Comment by jjsquillante** [comment]
@DBNoisemaker - 
When I fixed the syntax error at `line 42`, I was able to run and log todoList. I always forget to `run` plunkr in the top nav and then click `plunkrPreviewTarget`. Do you think this could have been the issue? sometimes it just takes fresh eyes.

**Comment by IvandCodes** [comment]
On line 42 you forgot to add an opening bracket after "if", the line should be:
```javascript
if (this.todos[i].completed === true){
```

**Comment by IvandCodes** [comment]
@DBNoisemaker , if you resolved this issue with the help of @jjsquillante, you can close this issue by yourself.

Cheers! :)

**Comment by gordonmzhu** [comment]
@IvandCodes Is correct. You have a syntax error in line 42. You should go back to the video where line 42 first appeared and make sure you have precisely the same code that I have in the videos.

**Comment by DBNoisemaker** [comment]
yup, forgot the (. 

thanks guys!
